apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app-from-source-6-test
  namespace: myproject
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: builder
          source:
            git:
              url: https://github.com/mchmarny/simple-app.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: test/app-from-source:latest
          timeout: 2m
      revisionTemplate:
        spec:
          container:
            image: test/app-from-source:latest
            imagePullPolicy: Always
            env:
              - name: SIMPLE_MSG
                value: "Hello from the sample app!"