apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: camel-simple-svc
  namespace: myproject
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            app: test
          annotations:
            alpha.image.policy.openshift.io/resolve-names: "*"
        spec:
          container:
            image: myproject/camel-simple:0.0.1
            readinessProbe:
              httpGet:
                path: /health
              initialDelaySeconds: 0
              periodSeconds: 1
