apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: knative-demo2-source
spec:
  consumerGroup: knative-group
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092 
  topics: knative-demo-topic
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display-2